import { lazy, ComponentType, LazyExoticComponent } from 'react'
import type { WidgetDef } from './widgetRegistry'

export type AppCategory = 'music' | 'games' | 'productivity' | 'utilities'

export interface AppDef {
  id: string
  name: string
  description: string
  path: string
  color: string
  gradient: string
  icon: string
  category: AppCategory
  component: LazyExoticComponent<ComponentType>
  widgets?: WidgetDef[]
}

export const apps: AppDef[] = [
  {
    id: 'youtubestreams',
    name: 'YouTube Streams',
    description: 'Play any YouTube stream — add custom streams, search & save favorites',
    path: '/youtubestreams',
    color: '#7c3aed',
    gradient: 'linear-gradient(135deg, #7c3aed, #ef4444)',
    icon: 'tabler:headphones',
    category: 'music',
    component: lazy(() => import('../apps/YouTubeStreams/YouTubeStreamsApp')),
    widgets: [
      {
        id: 'youtube-nowplaying',
        name: 'Now Playing',
        description: 'Currently playing YouTube stream',
        size: 'small',
        category: 'app',
        defaultActive: true,
        component: lazy(() => import('../apps/NowPlayingWidget/NowPlayingWidget')),
      },
    ],
  },
  {
    id: 'somafm',
    name: 'SomaFM Radio',
    description: '46 curated internet radio channels — ambient, electronic, lounge & more',
    path: '/somafm',
    color: '#d4763a',
    gradient: 'linear-gradient(135deg, #d4763a, #f0a757)',
    icon: 'tabler:antenna-bars-5',
    category: 'music',
    component: lazy(() => import('../apps/Somafm/SomafmApp')),
    widgets: [
      {
        id: 'somafm-nowplaying',
        name: 'Now Playing',
        description: 'Currently playing SomaFM channel',
        size: 'small',
        category: 'app',
        defaultActive: true,
        component: lazy(() => import('../apps/NowPlayingWidget/NowPlayingWidget')),
      },
    ],
  },
  {
    id: 'game2048',
    name: '2048',
    description: 'Merge tiles to reach 2048',
    path: '/game2048',
    color: '#d4763a',
    gradient: 'linear-gradient(135deg, #d4763a, #6b2fa0)',
    icon: 'tabler:layout-grid',
    category: 'games',
    component: lazy(() => import('../apps/Game2048/Game2048App')),
  },
  {
    id: 'todo',
    name: 'Todo List',
    description: 'Simple task manager — add, complete, prioritize, and filter tasks',
    path: '/todo',
    color: '#22c55e',
    gradient: 'linear-gradient(135deg, #22c55e, #06b6d4)',
    icon: 'tabler:list-check',
    category: 'productivity',
    component: lazy(() => import('../apps/Todo/TodoApp')),
    widgets: [
      {
        id: 'todo',
        name: 'Todo',
        description: 'Your pending tasks',
        size: 'small',
        category: 'app',
        defaultActive: true,
        component: lazy(() => import('../apps/TodoWidget/TodoWidget')),
      },
    ],
  },
  {
    id: 'pomodoro',
    name: 'Pomodoro',
    description: 'Focus timer with work/break intervals, session tracking & statistics',
    path: '/pomodoro',
    color: '#ef4444',
    gradient: 'linear-gradient(135deg, #ef4444, #f97316)',
    icon: 'tabler:clock',
    category: 'productivity',
    component: lazy(() => import('../apps/Pomodoro/PomodoroApp')),
    widgets: [
      {
        id: 'pomodoro',
        name: 'Pomodoro',
        description: 'Focus timer with controls',
        size: 'small',
        category: 'app',
        defaultActive: true,
        component: lazy(() => import('../apps/Pomodoro/PomodoroWidget')),
      },
    ],
  },
  {
    id: 'flappybird',
    name: 'Flappy Bird',
    description: 'Tap to fly! Dodge pipes and set your high score',
    path: '/flappybird',
    color: '#4dc9f6',
    gradient: 'linear-gradient(135deg, #4dc9f6, #73bf2e)',
    icon: 'lucide:bird',
    category: 'games',
    component: lazy(() => import('../apps/FlappyBird/FlappyBirdApp')),
  },
  {
    id: 'rssreader',
    name: 'RSS Reader',
    description: 'Aggregate and browse articles from multiple RSS feeds',
    path: '/rssreader',
    color: '#f97316',
    gradient: 'linear-gradient(135deg, #f97316, #eab308)',
    icon: 'tabler:rss',
    category: 'utilities',
    component: lazy(() => import('../apps/RssReader/RssReaderApp')),
    widgets: [
      {
        id: 'news',
        name: 'News',
        description: 'Latest headlines from your feeds',
        size: 'small',
        category: 'app',
        defaultActive: true,
        component: lazy(() => import('../apps/NewsWidget/NewsWidget')),
      },
    ],
  },
  {
    id: 'radiobrowser',
    name: 'Radio Browser',
    description: 'Browse & play thousands of radio stations from around the world',
    path: '/radiobrowser',
    color: '#22c55e',
    gradient: 'linear-gradient(135deg, #22c55e, #06b6d4)',
    icon: 'tabler:globe',
    category: 'music',
    component: lazy(() => import('../apps/RadioBrowser/RadioBrowserApp')),
    widgets: [
      {
        id: 'radiofav',
        name: 'Radio Favorite',
        description: 'Your favorite radio station',
        size: 'small',
        category: 'app',
        defaultActive: true,
        component: lazy(() => import('../apps/RadioFavWidget/RadioFavWidget')),
      },
    ],
  },
  {
    id: 'emulator',
    name: 'EmulatorJS',
    description: 'Play retro games — NES, SNES, GameBoy, N64, Sega, Atari, and more',
    path: '/emulator',
    color: '#9b59b6',
    gradient: 'linear-gradient(135deg, #9b59b6, #e74c3c)',
    icon: 'tabler:device-gamepad-2',
    category: 'games',
    component: lazy(() => import('../apps/EmulatorLauncher/EmulatorLauncherApp')),
  },
  {
    id: 'notes',
    name: 'Notes',
    description: 'Write and organize notes with live preview, folders, tags & markdown',
    path: '/notes',
    color: '#eab308',
    gradient: 'linear-gradient(135deg, #eab308, #f97316)',
    icon: 'tabler:file-text',
    category: 'productivity',
    component: lazy(() => import('../apps/Notes/NotesApp')),
    widgets: [
      {
        id: 'recent-notes',
        name: 'Recent Notes',
        description: 'Your latest notes',
        size: 'small',
        category: 'app',
        defaultActive: true,
        component: lazy(() => import('../apps/Notes/widgets/RecentNotesWidget/RecentNotesWidget')),
      },
    ],
  },
  {
    id: 'weather',
    name: 'Weather',
    description: 'Current weather & 7-day forecast — search cities, check conditions',
    path: '/weather',
    color: '#3b82f6',
    gradient: 'linear-gradient(135deg, #3b82f6, #06b6d4)',
    icon: 'tabler:sun',
    category: 'utilities',
    component: lazy(() => import('../apps/Weather/WeatherApp')),
    widgets: [
      {
        id: 'weather',
        name: 'Weather',
        description: 'Current weather conditions',
        size: 'medium',
        category: 'app',
        defaultActive: true,
        component: lazy(() => import('../apps/WeatherWidget/WeatherWidget')),
      },
      {
        id: 'uv',
        name: 'UV Index',
        description: 'Today\'s UV index',
        size: 'small',
        category: 'app',
        defaultActive: true,
        component: lazy(() => import('../apps/UvWidget/UvWidget')),
      },
      {
        id: 'moon',
        name: 'Moon Phase',
        description: 'Current moon phase',
        size: 'small',
        category: 'app',
        defaultActive: true,
        component: lazy(() => import('../apps/MoonWidget/MoonWidget')),
      },
      {
        id: 'aqi',
        name: 'Air Quality',
        description: 'Current air quality index',
        size: 'small',
        category: 'app',
        defaultActive: true,
        component: lazy(() => import('../apps/AqiWidget/AqiWidget')),
      },
    ],
  },
  {
    id: 'swappuzzle',
    name: 'Swap Puzzle',
    description: 'Swap tiles to recompose the photo — 3×3, 4×4 & 5×5 puzzles',
    path: '/swappuzzle',
    color: '#8b5cf6',
    gradient: 'linear-gradient(135deg, #8b5cf6, #ec4899)',
    icon: 'tabler:arrows-shuffle',
    category: 'games',
    component: lazy(() => import('../apps/SwapPuzzle/SwapPuzzleApp')),
  },
  {
    id: 'snake',
    name: 'Snake',
    description: 'Classic snake — eat, grow, and avoid crashing into walls or yourself',
    path: '/snake',
    color: '#22c55e',
    gradient: 'linear-gradient(135deg, #22c55e, #16a34a)',
    icon: 'tabler:bug',
    category: 'games',
    component: lazy(() => import('../apps/Snake/SnakeApp')),
  },
  {
    id: 'fifteenpuzzle',
    name: 'Photo Puzzle',
    description: 'Slide tiles to recompose a photo — 3×3, 4×4 & 5×5 puzzles',
    path: '/fifteenpuzzle',
    color: '#06b6d4',
    gradient: 'linear-gradient(135deg, #06b6d4, #8b5cf6)',
    icon: 'tabler:layout-grid',
    category: 'games',
    component: lazy(() => import('../apps/FifteenPuzzle/FifteenPuzzleApp')),
  },
  {
    id: 'wikipedia',
    name: 'Wikipedia',
    description: 'Search English Wikipedia — articles, people, places & more',
    path: '/wikipedia',
    color: '#636363',
    gradient: 'linear-gradient(135deg, #636363, #f5f5f5)',
    icon: 'lucide:book-open',
    category: 'utilities',
    component: lazy(() => import('../apps/Wikipedia/WikipediaApp')),
    widgets: [
      {
        id: 'wikionthisday',
        name: 'On This Day',
        description: 'Historical events on this date',
        size: 'medium',
        category: 'app',
        defaultActive: true,
        component: lazy(() => import('../apps/Wikipedia/WidgetOnThisDay')),
      },
      {
        id: 'wikididyouknow',
        name: 'Did You Know',
        description: 'Today\'s featured Wikipedia article',
        size: 'medium',
        category: 'app',
        defaultActive: true,
        component: lazy(() => import('../apps/Wikipedia/WidgetDidYouKnow')),
      },
      {
        id: 'wikithenews',
        name: 'In The News',
        description: 'Top news from Wikipedia',
        size: 'small',
        category: 'app',
        defaultActive: true,
        component: lazy(() => import('../apps/Wikipedia/WidgetInTheNews')),
      },
    ],
  },
  {
    id: 'hackernews',
    name: 'Hacker News',
    description: 'Browse top stories from Y Combinator — points, comments, saves & search',
    path: '/hackernews',
    color: '#ff6600',
    gradient: 'linear-gradient(135deg, #ff6600, #f97316)',
    icon: 'tabler:news',
    category: 'utilities',
    component: lazy(() => import('../apps/HackerNews/HackerNewsApp')),
    widgets: [
      {
        id: 'hackernews-top',
        name: 'HN Top Stories',
        description: 'Top stories from Hacker News',
        size: 'small',
        category: 'app',
        defaultActive: true,
        component: lazy(() => import('../apps/HackerNewsWidget/HackerNewsWidget')),
      },
    ],
  },
  {
    id: 'moodist',
    name: 'Moodist',
    description: '84 ambient sounds — focus, relax, and sleep with layered soundscapes',
    path: '/moodist',
    color: '#06b6d4',
    gradient: 'linear-gradient(135deg, #06b6d4, #7c3aed)',
    icon: 'tabler:wave-sine',
    category: 'music',
    component: lazy(() => import('../apps/Moodist/MoodistApp')),
    widgets: [
      {
        id: 'moodist-nowplaying',
        name: 'Now Playing',
        description: 'Currently playing ambient sound',
        size: 'small',
        category: 'app',
        defaultActive: true,
        component: lazy(() => import('../apps/NowPlayingWidget/NowPlayingWidget')),
      },
      {
        id: 'moodist-quickpreset',
        name: 'Quick Presets',
        description: 'Apply a saved ambient mix',
        size: 'small',
        category: 'app',
        defaultActive: true,
        component: lazy(() => import('../apps/MoodistWidgets/QuickPreset/QuickPresetWidget')),
      },
      {
        id: 'moodist-sleeptimer',
        name: 'Sleep Timer',
        description: 'Active sleep timer status',
        size: 'small',
        category: 'app',
        defaultActive: true,
        component: lazy(() => import('../apps/MoodistWidgets/SleepTimer/SleepTimerWidget')),
      },
      {
        id: 'moodist-soundboard',
        name: 'Soundboard',
        description: 'Quick access to favorite sounds',
        size: 'medium',
        category: 'app',
        defaultActive: false,
        component: lazy(() => import('../apps/MoodistWidgets/Soundboard/SoundboardWidget')),
      },
    ],
  },
  {
    id: 'kanban',
    name: 'Kanban',
    description: 'Visual project manager — boards, columns, cards, and drag & drop workflow',
    path: '/kanban',
    color: '#8b5cf6',
    gradient: 'linear-gradient(135deg, #8b5cf6, #3b82f6)',
    icon: 'tabler:layout-kanban',
    category: 'productivity',
    component: lazy(() => import('../apps/Kanban/KanbanApp')),
    widgets: [
      {
        id: 'kanban',
        name: 'Kanban',
        description: 'Board overview with column stats',
        size: 'medium',
        category: 'app',
        defaultActive: true,
        component: lazy(() => import('../apps/Kanban/KanbanWidget')),
      },
    ],
  },
  {
    id: 'calendar',
    name: 'Calendar',
    description: 'Smart calendar — events, deadlines, and important dates at a glance',
    path: '/calendar',
    color: '#3b82f6',
    gradient: 'linear-gradient(135deg, #3b82f6, #8b5cf6)',
    icon: 'lucide:calendar',
    category: 'productivity',
    component: lazy(() => import('../apps/Calendar/CalendarApp')),
    widgets: [
      {
        id: 'calendar',
        name: 'Calendar',
        description: 'Upcoming events',
        size: 'medium',
        category: 'app',
        defaultActive: true,
        component: lazy(() => import('../apps/CalendarWidget/CalendarWidget')),
      },
    ],
  },
]

export function getAppById(id: string): AppDef | undefined {
  return apps.find(a => a.id === id)
}

export function getAppByPath(path: string): AppDef | undefined {
  return apps.find(a => a.path === path)
}
